### ISSUE TITLE
Screw size for the hinges?

### ISSUE THREAD

**Issue by Retron101** [jeffqchen/PSone_LCD_Screen_Info#3]
Hello, do you know what is the right screw size for the hinges? I'm missing most of them and it might be useful to put them in the wiki.

**Comment by jeffqchen** [comment]
I didn't record the size of the screw. But it looks like it's a 2MM self-tapping screw. Not sure about the length but maybe 5mm or less? It's really shallow. The top is about 1.5mm thick and the diameter is 5mm.

**Comment by Retron101** [comment]
thank you, I found out the screw posts took M2.6x5mm screws.
